name: lint

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - '**.go'

jobs:
  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v1
        with:
          github_token: ${{ github.token }}
          level: warning
          filter_mode: nofilter
          reporter: github-pr-review